# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
